const routes = {
  home: '/',
  login: '/login',
  personal: '/personal/:tab?',
  lessons: '/lessons',
  lessonDetails: '/lessons/:id',
  lessonCreation: '/lessons/create',
  vrLessons: '/lessons/:id/:vrId',
  vrLessonDesign: '/vr-lessons-design',
  vrDevices: '/vr-devices',
  vrDeviceDetail: '/vr-devices/:id',
  myBundles: '/my-bundles',
  bundleImport: '/my-bundles/:orderId',
  accounts: '/accounts',
  accountDetail: '/accounts/:id',
  resources: '/resources',
  rsMasterSubjects: '/resources/master-subjects',
  rsSubjects: '/resources/subjects',
  rsMaps: '/resources/maps',
  rsLessons: '/resources/lessons',
  rsVrLessons: '/resources/vrlessons',
  rsMasterSubjectDetail: '/resources/master-subjects/:id',
  rsSubjectDetail: '/resources/subjects/:id',
  rsMapDetail: '/resources/maps/:id',
  rsLessonDetail: '/resources/lessons/:id',
  rsVrLessonDetail: '/resources/vrlessons/:id',
  adminDashboard: '/admin-dashboard',
  logout: '/logout',
  notFound: '*',
};

export default routes;
