import type { Lesson } from '@/common/types/lesson.type';
import type { Subject } from '@/common/types/subject.type';

export const SUBJECTS: Subject[] = [
  {
    id: 'chemistry',
    masterSubjectId: 'ms-001',
    name: 'Hóa học Cơ bản',
    masterSubjectName: 'Hóa học',
    description: 'Khám phá các phản ứng hóa học cơ bản và cách chúng hình thành thế giới vật chất xung quanh chúng ta.',
    imageUrl: '/images/subjects/basic-chemistry.jpg',
    status: 'active',
  },
  {
    id: 'physics',
    masterSubjectId: 'ms-002',
    name: 'Vật lý Cơ học',
    masterSubjectName: 'Vật lý',
    description: 'Giải thích các quy luật chuyển động và lực thông qua mô phỏng thực tế ảo sinh động.',
    imageUrl: '/images/subjects/physics-mechanics.jpg',
    status: 'active',
  },
  {
    id: 'biology',
    masterSubjectId: 'ms-003',
    name: 'Sinh học Tế bào',
    masterSubjectName: 'Sinh học',
    description: 'Khám phá cấu trúc và chức năng của tế bào thông qua mô phỏng 3D chân thực.',
    imageUrl: '/images/subjects/biology-cells.jpg',
    status: 'active',
  },
];

export const MOCK_LESSONS: Lesson[] = [
  {
    id: '1',
    subjectId: 'math',
    subjectName: 'Math',
    teacherId: 'teacher-1',
    name: 'Introduction to Calculus',
    description:
      'Learn the fundamentals of calculus including limits, derivatives, and integrals with interactive VR visualizations.',
    resourceRelativeFilePath: '/resources/calculus-101',
    status: 'published',
    createdAt: '2024-10-15T10:30:00Z',
    updatedAt: '2024-10-20T15:45:00Z',
    vrLessonsCount: 24,
    subjectImage: '/calculus-math-visualization.jpg',
  },
  {
    id: '2',
    subjectId: 'biology',
    subjectName: 'Biology',
    teacherId: 'teacher-1',
    name: 'Human Anatomy Explorer',
    description:
      'Explore the human body system in an immersive 3D VR environment. Discover organs, bones, and biological processes.',
    resourceRelativeFilePath: '/resources/anatomy-explorer',
    status: 'published',
    createdAt: '2024-10-10T09:15:00Z',
    updatedAt: '2024-10-18T14:20:00Z',
    vrLessonsCount: 18,
    subjectImage: '/human-anatomy-biology.jpg',
  },
  {
    id: '3',
    subjectId: 'chemistry',
    subjectName: 'Chemistry',
    teacherId: 'teacher-2',
    name: 'Molecular Structure Lab',
    description:
      'Interactive VR chemistry lab where students can build and manipulate molecular structures in 3D space.',
    resourceRelativeFilePath: '/resources/molecular-lab',
    status: 'published',
    createdAt: '2024-10-05T11:00:00Z',
    updatedAt: '2024-10-17T16:30:00Z',
    vrLessonsCount: 15,
    subjectImage: '/molecular-structure-chemistry.jpg',
  },
  {
    id: '4',
    subjectId: 'biology',
    subjectName: 'Biology',
    teacherId: 'teacher-1',
    name: 'Photosynthesis Process',
    description:
      'Understand photosynthesis through interactive VR simulations showing light reactions and the Calvin cycle.',
    resourceRelativeFilePath: '/resources/photosynthesis',
    status: 'published',
    createdAt: '2024-09-28T08:45:00Z',
    updatedAt: '2024-10-16T13:15:00Z',
    vrLessonsCount: 12,
    subjectImage: '/photosynthesis-plant-biology.jpg',
  },
  {
    id: '5',
    subjectId: 'math',
    subjectName: 'Math',
    teacherId: 'teacher-2',
    name: 'Geometry in 3D Space',
    description:
      'Discover geometric concepts by constructing and manipulating 3D shapes in an immersive VR environment.',
    resourceRelativeFilePath: '/resources/geometry-3d',
    status: 'draft',
    createdAt: '2024-10-12T07:30:00Z',
    updatedAt: '2024-10-19T10:00:00Z',
    vrLessonsCount: 9,
    subjectImage: '/3d-geometry-mathematics.jpg',
  },
  {
    id: '6',
    subjectId: 'chemistry',
    subjectName: 'Chemistry',
    teacherId: 'teacher-1',
    name: 'Periodic Table Elements',
    description: 'Journey through the periodic table with interactive 3D models and properties of each element.',
    resourceRelativeFilePath: '/resources/periodic-table',
    status: 'published',
    createdAt: '2024-09-20T14:20:00Z',
    updatedAt: '2024-10-14T12:45:00Z',
    vrLessonsCount: 20,
    subjectImage: '/periodic-table-chemistry-elements.jpg',
  },
];
